### ISSUE TITLE
Unable to deploy Wrangler via Docker Compose

### ISSUE THREAD

**Issue by sypion** [Receipt-Wrangler/receipt-wrangler-desktop#102]
Stack results in an error (via Portainer):
![image](https://github.com/Receipt-Wrangler/receipt-wrangler-desktop/assets/8906653/1d5e7551-90f7-4295-8a47-8c27d8d9ee68)

Adding `platform: linux/x86_64` under each service in the `docker_compose.yaml` also does not seem to resolve the problem. Tried on both macOS ARM and Raspberry Pi (x64, Debian).

**Comment by sypion** [comment]
It seems like API & Frontend do not have an image that supports ARM.

**Comment by Noah231515** [comment]
@sypion Give it a try now. Give https://github.com/Receipt-Wrangler a look for some examples of docker compose files for linux_arm. I got it running on an M1 mac. Had to use platform: linux/x86_64 on the desktop container.

Let me know if it works out for you!

**Comment by sypion** [comment]
Works great with Raspberry Pi! As for my M2 Mac, oddly enough I'm running into: `image with reference noah231515/receipt-wrangler-desktop:linux_arm64 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8`

**Comment by Noah231515** [comment]
@sypion I am now able to pull the most recent images without specifying platform in the docker compose. 
Is this the case for you as well?

**Comment by sypion** [comment]
Yes! Issue resolved. Running successfully using the `linux_arm64` image on both Raspberry Pi 64bit and an M2 Mac.
