### ISSUE TITLE
Cannot Register nor Sign In

### ISSUE THREAD

**Issue by sypion** [Receipt-Wrangler/receipt-wrangler-desktop#104]
Unable to register an account. An unknown error occurs and presents as so:
![image](https://github.com/Receipt-Wrangler/receipt-wrangler-desktop/assets/8906653/db16ba5c-64d3-4604-9ef6-b4acc1e59f1c)

Additionally, I can create a separate issue for this, but I am unable to see the "Sign up" button unless I'm visiting Wrangler from localhost. Might be something wrong with my Nginx Proxy Manager setup but it is similar to the one on the overview for this repo.

**Comment by Noah231515** [comment]
The issue with sign up is due to a typo in the feature config in the documentation. 
the feature "enabledLocalSignUp" should be "enableLocalSignUp". 

Additionally, check can you post screenshots of the error in the network tab of your browser? Those errors look like the api calls are not being forwarded correctly to the backend.

**Comment by sypion** [comment]
@Noah231515, here you are:
![image](https://github.com/Receipt-Wrangler/receipt-wrangler-desktop/assets/8906653/3d3bc59f-1fd5-45d7-8279-5218696894f3)

Looks like that's the case. I'm not entirely sure what to adjust besides my NPM.

**Comment by sypion** [comment]
Now that I was able to host Wrangler on my main machine (which is the M2 Mac Mini), I was able to properly proxy both the frontend and API and everything seems to working properly now. This is what I get, however, when I grab the log:

```
App2023/08/10 19:30:37 main.go:29: Initializing app...
App2023/08/10 19:30:37 main.go:70: Initialize completed
App2023/08/10 19:33:14 refresh_token.go:25: Refresh token cookie not found
App2023/08/10 19:33:14 refresh_token.go:25: Refresh token cookie not found
App2023/08/10 19:33:14 refresh_token.go:25: Refresh token cookie not found
App2023/08/10 19:33:14 refresh_token.go:25: Refresh token cookie not found
App2023/08/10 19:34:24 refresh_token.go:25: Refresh token cookie not found
App2023/08/10 19:34:24 refresh_token.go:25: Refresh token cookie not found
App2023/08/10 19:34:24 refresh_token.go:25: Refresh token cookie not found
App2023/08/10 19:34:24 refresh_token.go:25: Refresh token cookie not found
```

And for reference to anyone who has a similar setup to mine in terms of Nginx Proxy Manager, this is how I set that up:
<img width="496" alt="Screenshot 2023-08-10 at 12 38 29 PM" src="https://github.com/Receipt-Wrangler/receipt-wrangler-desktop/assets/8906653/74dd8ddb-d29e-4740-9981-5292c1fc6aeb">

I'm assuming the issue I was running into originally was because I had one machine (which hosts NPM) try to proxy Wrangler from another machine.

**Comment by Noah231515** [comment]
@sypion Glad everything seems to work now. 
What you're seeing in the log is expected. I will create an issue to clean up some of those token calls before logging in. I haven't updated the docs yet, logs directory is mountable now too. Should make it easier to debug in the future. I will also create an issue to make it play nice with docker log.

**Comment by sypion** [comment]
Perfect! I'll do more troubleshooting myself in the future for NPM, but for now, things seem to be working a-okay. I appreciate all your guidance.
