### ISSUE TITLE
Feature Request: Automatically magic fill upon upload

### ISSUE THREAD

**Issue by sypion** [Receipt-Wrangler/receipt-wrangler-desktop#107]
Wrangler's OpenAI integration is great. I'll be using magic fill every chance I'd get just to save myself time. Could there be an option per user to toggle "magic fill upon upload", rather than having to manually press to do so.

Edit: Additionally, since there doesn't seem to be a message for it, let the user know if magic fill could not obtain any details.

**Comment by Noah231515** [comment]
@sypion I like this idea. Currently I am working on a feature called quick scan which will allow users to scan an image, pick a user for paid by and it will magic fill, and save the receipt. If no data is found, valid defaults will be filled.

Does this satisfy this usecase?

They aren't really exclusive, but if a receipt has multiple images on a receipt (that is currently supported), then it may be annoying for it to be magic filled. Unless they were stitched together in the backend.

**Comment by sypion** [comment]
@Noah231515, I like where you're going. Instead of asking every time to pick a user for paid by, can it default to the owner/creator? Safe to say every receipt uploaded will not be used for splitting but rather for record keeping.

The same concept can be applied to `Status`, which can be `resolved` by default, and `Group` can be set to `Home`-- which would probably be better named "personal"-- or whichever group the receipt upload process is starting from.

I can't provide much further feedback/insight until [#95](https://github.com/Receipt-Wrangler/receipt-wrangler-api/issues/95) gets worked out haha.

**Comment by Noah231515** [comment]
@sypion Having defaults is a good idea. I think presenting the option to the user to select another user to charge to is a necessary, but prefilling said field with a default gets the best of both worlds.

In my case for example, I split a lot of bills between friends/SO and it is usually not one person everytime.

Having a default status behaves in the same way as the user (presenting the option to select one but defaulting to a user set value) is a good idea, for the sake of flexibility.

As an aside, groups can be managed by clicking on your user's avatar in the sidebar. It is quite hidden, and plan on moving the avatar elsewhere.

**Comment by sypion** [comment]
Sweet. At first I had trouble renaming the `Home` group and received error `App2023/08/12 04:11:01 groups.go:115: rename /go/api/data/1-Home /go/api/data/1-Personal: no such file or directory`.

Pulling `latest` seems to have fixed that.

**Comment by Noah231515** [comment]
@sypion Check out the latest versions of the api, and desktop. The initial implementation of quick scan has been merged. The next iteration will include configurable defaults.

**Comment by sypion** [comment]
So far so good! Looking forward to the next iteration.

**Comment by Noah231515** [comment]
@sypion Quick scan defaults have been added in the latest version 🥳🥳
