### ISSUE TITLE
Logs, email, debugging and lack of documentation

### ISSUE THREAD

**Issue by zallaevan** [Receipt-Wrangler/receipt-wrangler-desktop#284]
I have stumbled across this project, and please let me congratulate you first for your hard work. It is a very nice execution of a solution to a problem that many people will have in their daily lives, as it is in my case. I wanted to credit your dedication to this project before spitting out a few things that could help in the development.
After installing it via the monolithic container and hosting it on Docker, I have met the following difficulties:

- Not enough verbosity in logs: I set up the email server, but it shows me that it can't connect to the server. No further reason nor errors have been displayed. This bugs (pun intended) me out as I cannot debug and find where is the underlying cause of the error. I have tested my configuration parameters with other software and it works flawlessly.

- There is a lack of documentation about the initial setup: no recommended length or security implications and requirements for encryption keys are shown, only that there is a mandatory need to declare such variables. This can be quite unfriendly for new or inexperienced system managers. There is also a lack of details in the system requirements part, as I did not know an AI was needed for it in order to work properly, which brings up the following issue too:
- A lack of documentation about the configuration and setup of the instance: I have not found any information on the wiki/docs regarding the setting of "Receipt Processing Settings". After reading the changelog, I have deduced that it is a main part of the program's functionality and that the "prompts" are an essential part of the AI processing. This can be misleading, as it is never mentioned in the documentation apart from the "custom/self-hosted AI" section. I also think it might be helpful to add a few "default" or "model" prompts in order to let users know what type of prompts the AI is expecting or how to make out most of the AI feature.
- It would be very nice to have a _dark mode_ for the web interface too!
- Maybe add a way to export the current settings and data structure? LIke in JSON format of similar for ease of use.

Although I might have ranted about a few issues here, it is still a very nice program, and I don't want to disincentivise any motivation.

**Comment by Noah231515** [comment]
Hey thanks for the feedback, and for checking out Receipt Wrangler.

- Thanks for pointing this out. Not too long ago, I rewrote logging in the API to spit out errors via stdout so they will show up in the docker logs. I don't think I made that change in the email client. There are logs in the logs/imap-client.log which will contain more information. Additionally, if you create an email, and check connectivity, you will be able to see the error if there was one. At times, it is not that helpful though depending on what actually went wrong.
- This is a good point, I will add some more detail around the security implications. AI is not needed to use Receipt Wrangler, the features that AI enable is detailed here: https://receiptwrangler.io/docs/concepts/ai , but I agree that it is not totally clear, I'll make some adjustments to the documentation.
- There is documentation regarding Receipt Processing Settings, and Prompts here: https://receiptwrangler.io/docs/category/system-settings as well as the default prompt that can be created in app already, as well as an example of a prompt that itemizes, and everything you would want to know to build prompts.
- Import/Exporting settings is a fantastic idea. I will add a backlog item for this.

Let me know if I can help out with anything.

**Comment by zallaevan** [comment]
Hi again:
I didn't realize that there was a _concepts_ part in the documentation, sorry for the confusion. I have tried creating a default prompt but I am unable to use it as I am not in possession of any valid API key (can't afford it, student). I am looking forward to setting up my own ollama instance but I think it might be quite overkill for such a niche use case. 
Anyway, there are still issues that I have not been able to solve:
- The mentioned imap-client.log is nowhere to be found. I have checked the volume and the current directory but no trace of it.

I tried to add a new receipt without setting any AI or tweaking any configuration, and I am kind of lost here: I am able to add tickets, but I thought there would be a place to add each item and info about the ticket manually without the need of OCR+AI use.
Another thing I wanted to comment on was regarding the Android app: there is currently no way of adding receipts manually, they can be added only via the quickscan function. I propose to add a _manual_ way to add items to each receipt and then, in this way, the function might be used in the phone app for manual ticket registration too! Sometimes, I might need to only upload a photo as a receipt and no itemization is needed so the mandatory use of quickscan in the app can be almost counterproductive.

As a side note, including a dark mode will also be phenomenal!

Z,E,

**Comment by Noah231515** [comment]
Thanks for the feedback, I created a bug to fix the missing imap-client.log, should be there upon container creation.

Not totally clear on if you are using the desktop app, or the mobile app, but on desktop you can use Receipt Wrangler without AI, the documentation details what features are enabled with AI https://receiptwrangler.io/docs/concepts/ai.

As for the mobile app, the documentation states that the app is in early access, and lists the functionality that is currently available, see https://receiptwrangler.io/mobile-app-registration. Receipts can be added manually without AI/OCR in desktop but currently cannot in the app because it is still being developed.
